### ISSUE TITLE
Shape HOC

### ISSUE THREAD

**Issue by jsnelgro** [jsnelgro/vzy#2]
Todo
=====
- [x] use the following props interface (API lifted from Affinity Designer's transform module)
```
props:
  height: number
  width: number
  x: number
  y: number
  rotation: number
  origin: string
  skew: number
```
- [x] test using composite shapes (it's useless if creating composite shapes isn't intuitive)
- [x]  write storybook examples
- [x] fix shape components
- [ ] write documentation
